# Generated by Django 4.1.4 on 2022-12-07 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reserva_Inicial1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivo', models.CharField(blank=True, max_length=60, null=True)),
                ('direccion', models.CharField(blank=True, max_length=60, null=True)),
                ('foto_tacometro1', models.ImageField(blank=True, null=True, upload_to='reservas/media')),
            ],
        ),
        migrations.CreateModel(
            name='Reserva_Inicial2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivo', models.CharField(blank=True, max_length=60, null=True)),
                ('direccion', models.CharField(blank=True, max_length=60, null=True)),
                ('foto_tacometro2', models.ImageField(blank=True, null=True, upload_to='reservas/media')),
            ],
        ),
    ]
